/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 playerFinal.gltf 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/playerFinal.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig">
          <primitive object={nodes.spine} />
          <primitive object={nodes.neutral_bone} />
          <group name="Object_2018">
            <skinnedMesh name="Object_0018" geometry={nodes.Object_0018.geometry} material={materials.Glock_Mat4} skeleton={nodes.Object_0018.skeleton} />
            <skinnedMesh name="Object_0018_1" geometry={nodes.Object_0018_1.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Object_0018_1.skeleton} />
            <skinnedMesh name="Object_0018_2" geometry={nodes.Object_0018_2.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Object_0018_2.skeleton} />
            <skinnedMesh name="Object_0018_3" geometry={nodes.Object_0018_3.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Object_0018_3.skeleton} />
            <skinnedMesh name="Object_0018_4" geometry={nodes.Object_0018_4.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Object_0018_4.skeleton} />
            <skinnedMesh name="Object_0018_5" geometry={nodes.Object_0018_5.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Object_0018_5.skeleton} />
            <skinnedMesh name="Object_0018_6" geometry={nodes.Object_0018_6.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Object_0018_6.skeleton} />
            <skinnedMesh name="Object_0018_7" geometry={nodes.Object_0018_7.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.Object_0018_7.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/playerFinal.gltf')
