/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 gunHand.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gunHand.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.003, 0.578, -0.156]} rotation={[-1.136, -0.05, -0.106]}>
        <mesh geometry={nodes.Object_0108.geometry} material={materials.Wolf3D_Body} />
        <mesh geometry={nodes.Object_0108_1.geometry} material={materials.Glock_Mat4} />
      </group>
    </group>
  )
}

useGLTF.preload('/gunHand.gltf')
