/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 chair.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Chair(props) {
  console.log(props.userData);
  const { nodes, materials } = useGLTF("/models/chair/chair.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        userData={props.userData}
        geometry={nodes.Cube026.geometry}
        material={materials.lambert2}
      />
    </group>
  );
}

useGLTF.preload("/chair.gltf");
