/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 chair.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Chair(props) {
  const { nodes, materials } = useGLTF('/models/chair/chair.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube026.geometry} material={materials.lambert2} position={[0, 1.4, 0]} />
    </group>
  )
}

useGLTF.preload('/chair.gltf')
