/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 chair.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Chair(props) {
  const { nodes, materials } = useGLTF('/models/chair/chair.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_74.geometry} material={materials.lambert2} rotation={[Math.PI, 0, Math.PI]} scale={2.4} />
    </group>
  )
}

useGLTF.preload('/models/chair/chair.gltf')
