/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 player.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Player(props) {
  const { nodes, materials } = useGLTF('/models/player/player.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.916}>
        <primitive object={nodes.spine} />
        <skinnedMesh geometry={nodes.Object_74.geometry} material={materials.Wolf3D_Avatar} skeleton={nodes.Object_74.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/player.gltf')
